import HeaderOne from "@/Component/header1";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderOne/>
        {children}
        </body>
    </html>
  );
}
